--Bang Phan Quyen
CREATE TABLE PHANQUYEN(
    MaNhom VARCHAR2(50) NOT NULL,
    MaChucNang VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PHANQUYEN PRIMARY KEY(MaNhom, MaChucNang)
)
INSERT INTO PHANQUYEN VALUES ('NND01','QLTK');
INSERT INTO PHANQUYEN VALUES ('NND02','HSDL');
INSERT INTO PHANQUYEN VALUES ('NND02','TTQD');
INSERT INTO PHANQUYEN VALUES ('NND03','HSDL');
INSERT INTO PHANQUYEN VALUES ('NND03','QLNH');
INSERT INTO PHANQUYEN VALUES ('NND03','QLXH');
INSERT INTO PHANQUYEN VALUES ('NND03','QLPT');
INSERT INTO PHANQUYEN VALUES ('NND03','BCTK');



