--Bang Quan
CREATE TABLE QUAN(
    MaQuan VARCHAR2(50) PRIMARY KEY,
    TenQuan VARCHAR2(255) NOT NULL
)
--Insert Quan
INSERT INTO QUAN VALUES ('Q1', 'Qu?n 1');
INSERT INTO QUAN VALUES ('Q2', 'Qu?n 2');
INSERT INTO QUAN VALUES ('Q3', 'Qu?n 3');
INSERT INTO QUAN VALUES ('Q4', 'Qu?n 4');
INSERT INTO QUAN VALUES ('Q5', 'Qu?n 5');