--Bang Chi Tiet Phieu Xuat
CREATE TABLE CHITIETPHIEUXUAT(
    Ma_CTPX NUMBER PRIMARY KEY NOT NULL,
    MaPhieuXuat VARCHAR2(50) NOT NULL,
    MaMatHang VARCHAR2(50) NOT NULL,
    SoLuong NUMBER NOT NULL,
    DonGiaXuat NUMBER NOT NULL,
    ThanhTien NUMBER NOT NULL
)
DROP TABLE CHITIETPHIEUXUAT;
CREATE SEQUENCE SEQ_CHITIETPHIEUXUAT START WITH 1;

INSERT INTO CHITIETPHIEUXUAT VALUES (SEQ_CHITIETPHIEUXUAT.NEXTVAL, 'PX01', 'MH01', 50, 20400,1020000);
INSERT INTO CHITIETPHIEUXUAT VALUES (SEQ_CHITIETPHIEUXUAT.NEXTVAL, 'PX01', 'MH02', 50, 81600,4080000);

