--Bang Don Vi Tinh
CREATE TABLE DONVITINH(
    MaDonViTinh VARCHAR2(50)PRIMARY KEY,
    TenDonViTinh VARCHAR2(255) NOT NULL
)
--Insert Don Vi Tinh
INSERT INTO DONVITINH VALUES('DVM',N'Mét khối');
INSERT INTO DONVITINH VALUES('DVB',N'Bao');
INSERT INTO DONVITINH VALUES('DVV',N'Viên');
INSERT INTO DONVITINH VALUES('DVC',N'Cuộn');
INSERT INTO DONVITINH VALUES('DVK','Kilogam');
