--Bang Nhom Nguoi Dung
CREATE TABLE NHOMNGUOIDUNG(
    MaNhom VARCHAR2(50) PRIMARY KEY NOT NULL,
    TenNhom VARCHAR2(50) NOT NULL
)
INSERT INTO NHOMNGUOIDUNG VALUES ('NND01','Quan ly');
INSERT INTO NHOMNGUOIDUNG VALUES ('NND02','Nhan vien');


