--Bang Phieu Thu Tien
CREATE TABLE PHIEUTHUTIEN(
    MaPhieuThuTien NUMBER PRIMARY KEY NOT NULL,
    MaPhieuXuat VARCHAR2(50) NOT NULL,
    NgayThuTien DATE NOT NULL,
    SoTienThu NUMBER NOT NULL
)
SELECT*FROM PHIEUTHUTIEN;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
CREATE SEQUENCE SEQ_PHIEUTHUTIEN START WITH 1;

INSERT INTO PHIEUTHUTIEN VALUES(SEQ_PHIEUTHUTIEN.NEXTVAL,'DL002','30/01/2022',692000);
INSERT INTO PHIEUTHUTIEN VALUES(SEQ_PHIEUTHUTIEN.NEXTVAL,'DL003','30/01/2022',2000000);
INSERT INTO PHIEUTHUTIEN VALUES(SEQ_PHIEUTHUTIEN.NEXTVAL,'DL003','14/02/2022',1160000);
