--Bang Quan
CREATE TABLE QUAN(
    MaQuan VARCHAR2(50) PRIMARY KEY,
    TenQuan VARCHAR2(255) NOT NULL
)
--Insert Quan
INSERT INTO QUAN VALUES ('Q1', 'Quận 1');
INSERT INTO QUAN VALUES ('Q2', 'Quận 2');
INSERT INTO QUAN VALUES ('Q3', 'Quận 3');
INSERT INTO QUAN VALUES ('Q4', 'Quận 4');
INSERT INTO QUAN VALUES ('Q5', 'Quận 5');