package View;
import Connection.ConnectionJDBC;

import Connection.ConnectionUtils;
import java.awt.event.ActionEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import javax.swing.JOptionPane;

/**
 *
 * @author NDAT_UIT
 */
public class BaoCaoCongNo extends javax.swing.JFrame {

    /**
     * Creates new form QuyCheToChuc_TN
     */
    public BaoCaoCongNo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabeltongnocuoi = new javax.swing.JLabel();
        jLabelnocuoi = new javax.swing.JLabel();

        jLabelthang = new javax.swing.JLabel();
        jLabelnam = new javax.swing.JLabel();
        jTextFieldthang = new javax.swing.JTextField();
        jTextFieldnam = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButtonxuat = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setBackground(new java.awt.Color(204, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Báo cáo công nợ");

        jButton3.setBackground(new java.awt.Color(204, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Báo cáo doanh số");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonxuat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonxuat.setText("Xuất");
        jButtonxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonxuatActionPerformed(evt);
            }
        });

        
        jPanel1.setBackground(new java.awt.Color(204, 229, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelthang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelthang.setText("Tháng");
        
        jLabeltongnocuoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelnocuoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelnam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelnam.setText("Năm");

        jTextFieldthang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldnam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã loại đại lý");
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã đại lý", "Nợ đầu", "Phát sinh","Nợ cuối"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        
        jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelthang))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldthang,javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                ))      
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelnam))
                                .addGap(32,32,32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                	.addComponent(jTextFieldnam, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    ))              
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabeltongnocuoi)

                                .addComponent(jLabelnocuoi)
                                )

                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(170,170,170)
                        		.addComponent(jButtonxuat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelthang)
                        .addComponent(jTextFieldthang,javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnam)
                            .addComponent(jTextFieldnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                    .addGap(15, 15, 15)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addGap(15, 15, 15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltongnocuoi)
                            .addComponent(jLabelnocuoi))
                    .addGap(10,10,10)
                    .addComponent(jButtonxuat)
                    .addContainerGap()
                    .addGap(30,30,30))
            );


        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setBackground(new java.awt.Color(230, 230, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/quydinh_64px.png"))); // NOI18N
        jLabel2.setText("Báo cáo công nợ");
        jLabel2.setToolTipText("");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon_64px.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButton4)
                .addGap(99, 99, 99)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jButton4))
                .addGap(25, 25, 25))
        );

        layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                    	.addGap(30,30,30)
                    	.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40,40,40))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
        

    }// </editor-fold>//GEN-END:initComponents
    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    	if (evt.getSource() == jButton3) {
    		this.dispose();
    		new BaoCaoDoanhSo().setVisible(true);
    	}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonxuatActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if (evt.getSource() == jButtonxuat) {
    		try (Connection conn = ConnectionUtils.getMyConnection()) 
    		{
    			long nocuoi = 0;
                if (conn != null) {
                	if (jTextFieldthang.getText().isBlank() & !jTextFieldnam.getText().isBlank())
                	{
                		try {
                        System.out.println("Connected to the database!");                    
    	    			String query_daily = "select * from daily";
    	    			
    	    			int index_madaily = 0;
                        Statement stdl =  conn.createStatement();
                        ResultSet rsdl = stdl.executeQuery(query_daily);
    	    			String[] madaily = new String[100];

                        while (rsdl.next()) {
                        	madaily[index_madaily] = rsdl.getString("madaily");
                        	index_madaily += 1;
                        }
                        
                        int index_queries = 0;

    	    			for (int i = 0; i< index_madaily;i++) {
    		    			CallableStatement cstmt;
    		    			cstmt = conn.prepareCall("{call Pro_BaoCaoCongNoNam(?,?,?,?,?)}");

    		    			cstmt.setString(1, madaily[i]);
    		    			cstmt.setInt(2, Integer.parseInt(jTextFieldnam.getText()));
    		    			cstmt.registerOutParameter(3, Types.INTEGER);
    		    			cstmt.registerOutParameter(4, Types.INTEGER);
    		    			cstmt.registerOutParameter(5, Types.INTEGER);
    		    			cstmt.executeUpdate();
    		    			
                            String[] value = new String[100];
                            value[0] = madaily[i];
                        	value[1] = Integer.toString(cstmt.getInt(3));
                        	value[2] = Integer.toString(cstmt.getInt(4));
                        	value[3] = Integer.toString(cstmt.getInt(5));
                        	nocuoi += Integer.parseInt(value[3]);
                        	queries[index_queries] = value;
                        	index_queries += 1;

    	    			}
                        
                        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        		queries,
                                new String [] {
                                       "Mã đại lý", "Nợ đầu", "Phát sinh", "Nợ cuối"
                                }
                            ));
                        jLabelnocuoi.setForeground(new java.awt.Color(0, 51, 255));
                        jLabeltongnocuoi.setForeground(new java.awt.Color(0, 51, 255));

                        jLabelnocuoi.setText(String.valueOf(nocuoi));
                        
                        jLabeltongnocuoi.setText("Tổng nợ cuối: ");

                        return;
                		}
                    	catch(NumberFormatException n) {
                    		JOptionPane.showMessageDialog(null,
                                    "Vui lòng nhập số",
                                    "ERROR",
                                    JOptionPane.ERROR_MESSAGE);
                        	return;

                    	}
                	}
                	
                	try {
                	if (Integer.parseInt(jTextFieldthang.getText()) > 12 || Integer.parseInt(jTextFieldthang.getText()) < 1) {
                    	JOptionPane.showMessageDialog(null,
                                "Vui lòng nhập đúng định dạng tháng",
                                "ERROR",
                                JOptionPane.ERROR_MESSAGE);
                    	return;

                	}
                	
                    System.out.println("Connected to the database!");                    
	    			String query_daily = "select * from daily";
	    			
	    			int index_madaily = 0;
                    Statement stdl =  conn.createStatement();
                    ResultSet rsdl = stdl.executeQuery(query_daily);
	    			String[] madaily = new String[100];

                    while (rsdl.next()) {
                    	madaily[index_madaily] = rsdl.getString("madaily");
                    	index_madaily += 1;
                    }
                    
                    int index_queries = 0;

	    			for (int i = 0; i< index_madaily;i++) {
		    			CallableStatement cstmt;
		    			cstmt = conn.prepareCall("{call Pro_BaoCaoCongNo(?,?,?,?,?,?)}");

		    			cstmt.setString(1, madaily[i]);
		    			cstmt.setInt(2, Integer.parseInt(jTextFieldnam.getText()));
		    			cstmt.setInt(3, Integer.parseInt(jTextFieldthang.getText()));
		    			cstmt.registerOutParameter(4, Types.INTEGER);
		    			cstmt.registerOutParameter(5, Types.INTEGER);
		    			cstmt.registerOutParameter(6, Types.INTEGER);
		    			cstmt.executeUpdate();
		    			
                        String[] value = new String[100];
                        value[0] = madaily[i];
                    	value[1] = Integer.toString(cstmt.getInt(4));
                    	value[2] = Integer.toString(cstmt.getInt(5));
                    	value[3] = Integer.toString(cstmt.getInt(6));
                    	nocuoi += Integer.parseInt(value[3]);

                    	queries[index_queries] = value;
                    	index_queries += 1;

	    			}
                    
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    		queries,
                            new String [] {
                                   "Mã đại lý", "Nợ đầu", "Phát sinh", "Nợ cuối"
                            }
                        ));
                    jLabelnocuoi.setForeground(new java.awt.Color(0, 51, 255));
                    jLabeltongnocuoi.setForeground(new java.awt.Color(0, 51, 255));

                    jLabelnocuoi.setText(String.valueOf(nocuoi));
                    
                    jLabeltongnocuoi.setText("Tổng nợ cuối: ");

                    }
                	catch(NumberFormatException n) {
                		JOptionPane.showMessageDialog(null,
                                "Vui lòng nhập số",
                                "ERROR",
                                JOptionPane.ERROR_MESSAGE);
                    	return;

                	}

                } else {
                    System.out.println("Failed to make connection!");
                }

            } catch (SQLException e) {
                System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
                 
            } catch (Exception e) {
                e.printStackTrace();
            }		

    	}
    }                                        
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    	if (evt.getSource() == jButton4) {
    		if (truycap.quyentruycap.equals("NND01")) {
    			new Home().setVisible(true);
    			this.dispose();
    		}
    		else if (truycap.quyentruycap.equals("NND02")) {
    			new Home_NhanVien().setVisible(true);
    			this.dispose();
    		}
    	}
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCaoCongNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCaoCongNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCaoCongNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCaoCongNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCaoCongNo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonxuat;

    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelthang;
    private javax.swing.JLabel jLabelnam;
    private javax.swing.JLabel jLabeltongnocuoi;
    private javax.swing.JLabel jLabelnocuoi;

    private javax.swing.JTextField jTextFieldnam;
    private javax.swing.JTextField jTextFieldthang;

    
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    javax.swing.GroupLayout jPanel1Layout;
    javax.swing.GroupLayout layout;
    javax.swing.GroupLayout jPanel3Layout;
    
    private String[][] queries = new String[100][];

}
