/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Connection.ConnectionJDBC;

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Connection.ConnectionUtils;
/**
 *
 * @author minhv
 */
public class ctnh extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ctnh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        jComboBox1 = new javax.swing.JComboBox<String>();

        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabeldongia = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextFielddongia = new javax.swing.JTextField();

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButtonin =  new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(217, 198, 236));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Chi tiết nhập hàng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mã Phiếu Nhập");
        
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mã CT Phiếu Nhập");

        jLabeldongia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeldongia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeldongia.setText("Đơn Giá Nhập");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextFielddongia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFielddongia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField2.setText(truycap.maphieunhap);
        
        jButton5.setBackground(new java.awt.Color(217, 198, 236));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clear_32px.png"))); // NOI18N
        jButton5.setText("Xoá");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        
        jButtonin.setBackground(new java.awt.Color(217, 198, 236));
        jButtonin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clear_32px.png"))); // NOI18N
        jButtonin.setText("In");
        jButtonin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninActionPerformed(evt);
            }
        });


        jButton6.setBackground(new java.awt.Color(217, 198, 236));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/undo_32px.png"))); // NOI18N
        jButton6.setText("Quay Lại");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(217, 198, 236));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_32px.png"))); // NOI18N
        jButton7.setText("Thêm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(217, 198, 236));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)), "TÌM KIẾM PHIẾU NHẬP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)));
        jPanel4.setToolTipText("YUJ");
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(217, 198, 236));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        jButton3.setText("Tìm Kiếm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel11))
        );

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            	
            },
            new String [] {
                "Mã CT Phiếu Nhập", "Mã Phiếu Nhập", "Mã Mặt Hàng", "Số Lượng", "Đơn Giá Nhập", "Thành Tiền"
            }
        ));
        
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        

        jTable1.setToolTipText("");
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);
        try (Connection conn = ConnectionUtils.getMyConnection()){
            if (conn != null) {
                System.out.println("Connected to the database!");
                Statement st =  conn.createStatement();
                ResultSet rs;
                
                rs = st.executeQuery("select max(Ma_ctpn) from chitietphieunhap ");                
                
                while (rs.next()) {
                	first_index = rs.getInt("max(Ma_ctpn)");
                }

                
                ArrayList<String> amathang = new ArrayList();
                int id1 = 0;
                Statement st1 =  conn.createStatement();
                ResultSet rs1;

                rs1 = st1.executeQuery("select * from mathang order by mamathang");                
                while (rs1.next()) {
                	amathang.add(rs1.getString("mamathang"));
                }
                String[] mathang = new String[amathang.size()];
                mathang = amathang.toArray(mathang);
                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(mathang));

                
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        queries,
                        new String [] {
                                "Mã CT Phiếu Nhập", "Mã Phiếu Nhập", "Mã Mặt Hàng", "Số Lượng", "Đơn Giá Nhập", "Thành Tiền"
                        }
                    ));

            }
        }catch (SQLException ex) {
            Logger.getLogger(ctnh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Thành Tiền");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Số lượng");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mã mặt hàng");

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

//        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
//        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel10.setText("Nhà Cung Cấp");

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

//        jButton8.setBackground(new java.awt.Color(217, 198, 236));
//        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
//        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update_32px.png"))); // NOI18N
//        jButton8.setText("Cập Nhật");
//        jButton8.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton8ActionPerformed(evt);
//            }
//        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabeldongia))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFielddongia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButton7)
                                .addGap(110, 110, 110)
                                .addComponent(jButton5)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(65,65,65)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButtonin))

                    )
                .addContainerGap()
                )
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton6)
                    )
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielddongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeldongia)
                    )
            	.addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                	.addComponent(jButton7)
                    .addComponent(jButton5)

                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
//                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonin))
        );

        jPanel4.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jButton6) {
            this.dispose();
            new QuanLyNhapHang().setVisible(true);
	}
    }//GEN-LAST:event_jButton6ActionPerformed

    private int countBlank(String[] arr) {
    	int count = 0;
    	for (int i =0;i<=5;i++) {
    		if (arr[i].isBlank())
    			count +=1;
    	}
    	return count;
    }
    private int countNull(String[] arr) {
    	int count = 0;
    	for (int i =0;i<=5;i++) {
    		if (arr[i]== null)
    			count +=1;
    	}
    	return count;
    }

    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    	// them
        if (evt.getSource() == jButton7){
        	boolean hasmh = false;
        	boolean hasphieunhap = false;
            String[] value = new String[6];

            try (Connection conn = ConnectionUtils.getMyConnection()){   
                if (conn != null) {
                    System.out.println("Connected to the database!");
                    Statement st1 =  conn.createStatement();
                    ResultSet rs;
                    String mactpn = null;
                    String mapn = null;
                    String mathang = null;
                    String soluong = null;
                    String dongianhap = null;
                    try {
                    	mactpn = "SEQ_CHITIETPHIEUNHAP.nextval";
                    	mapn = truycap.maphieunhap;
                    	System.out.println(mapn);
                    	mathang = (String) jComboBox1.getModel().getSelectedItem();
                    	soluong = jTextField10.getText();
                    	
                    	
                    	value[0] = String.valueOf(first_index);
                    	value[1] = mapn;
                    	value[2] = mathang;
                    	value[3] = soluong;
                    	
                        Statement stmh =  conn.createStatement();
                        ResultSet rsmh ;
                        String query_mathang = "select * from mathang ";
                        System.out.println(query_mathang);
                        System.out.println(query_mathang);
                        rsmh = stmh.executeQuery(query_mathang);
                        while (rsmh.next()) {
                        	if (mathang.equals(rsmh.getString("mamathang"))){
                        		hasmh = true;

            				}
                        }
                        dongianhap = jTextFielddongia.getText();
                        value[4] = dongianhap;
                        int summ = Integer.parseInt(dongianhap) *  Integer.parseInt(soluong);
                    	value[5] = String.valueOf(summ);
                    	
                        
                        if (!hasmh) {
                            JOptionPane.showMessageDialog(null,
                                    "Mặt hàng không tồn tại",
                                    "ERROR",
                                    JOptionPane.ERROR_MESSAGE);
                            return;
                        }

                        
                        
                    	if (Integer.parseInt(soluong) <= 0 ) {
	                        JOptionPane.showMessageDialog(null,
	                                "Vui lòng nhập số lượng dương",
	                                "ERROR",
	                                JOptionPane.ERROR_MESSAGE);
	                        return;

                    	}

                    	if (countBlank(value) >0 || countNull(value) >0) {
	                        JOptionPane.showMessageDialog(null,
	                                "Vui lòng nhập đúng và đầy đủ thông tin về chi tiết phiếu nhập",
	                                "ERROR",
	                                JOptionPane.ERROR_MESSAGE);
	                        return;
	                    }

                    }
                    catch (Exception e) {
        	            e.printStackTrace();
        	            JOptionPane.showMessageDialog(null,
	                                "Vui lòng nhập đúng và đầy đủ thông tin về chi tiết phiếu nhập",
	                                "ERROR",
	                                JOptionPane.ERROR_MESSAGE);
	                        return;

                    }
                                        
                    Statement st2 =  conn.createStatement();

                    String query1 = "insert into chitietphieunhap values (" + "" + mactpn + "" + "," + "\'" + mathang + "\'" + "," + "\'" + mapn + "\'" + "," + soluong + "," + dongianhap +","+ value[5]  + ")";
                    System.out.println(query1);

                    st2.executeUpdate(query1);
                    System.out.println(query1);
                    String query2 = "update mathang set soluongton = soluongton + " +  soluong + ", dongianhap = " + dongianhap +  " where mamathang = " + "\'" + mathang +"\'";
                    System.out.println(query2);

                    Statement st3 =  conn.createStatement();

                    st3.executeQuery(query2);
                    tongtien += Integer.valueOf(value[5]);
                    queries[index] = value;
                    index += 1;
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                            queries,
                            new String [] {
                                    "Mã CT Phiếu Nhập", "Mã Phiếu Nhập", "Mã Mặt Hàng", "Số Lượng", "Đơn Giá Nhập", "Thành Tiền"
                            }
                        ));
                    first_index += 1;

//                    String query3 = "update PHIEUNHAPHANG set tongtien = tongtien + " + value[5]  + "where maphieunhap = " + "\'" + mapn +"\'";
//                    st1.execute(query3);


                }
                else{
                    System.out.println("Failed to make connection!");      
                }
            } catch (SQLException ex) {
                if (ex.getSQLState().equals("23000"))
                    JOptionPane.showMessageDialog(null,
                            "Mã Chi Tiết Phiếu Nhập Đã Tồn Tại",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                return;
            } catch (ClassNotFoundException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}  

        }
        JOptionPane.showMessageDialog(null,
                "Nhập thành công",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        return;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        int sl = Integer.parseInt(jTextField8.getText());
        int dongianhap = Integer.parseInt(jTextField10.getText());
        jTextField9.setText(Integer.toString(sl * dongianhap));
        
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
        
//        Connection conn;
//        try {
//            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "system", "1");
//            Statement st =  conn.createStatement();
//            ResultSet rs;
//            String mathang = jTextField11.getText();
//            String query1 = "select dongianhap from mathang where mamathang = " + "\'"+ mathang + "\'";
//            rs = st.executeQuery(query1);
//            int dongianhap = 0 ;
//            while (rs.next()) {
//                dongianhap = rs.getInt("DONGIANHAP");
//            }
//            jTextField10.setText(Integer.toString(dongianhap));
//        } catch (SQLException ex) {
//            System.out.println(ex);
//        }
                
            
            
        
        

    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    	// tim kiem
        if (evt.getSource() == jButton3){
            try (Connection conn = ConnectionUtils.getMyConnection()){
                if (conn != null) {
                    System.out.println("Connected to the database!");
                    Statement st =  conn.createStatement();
                    ResultSet rs;
                    String mapn = jTextField5.getText();
                    if (mapn.isBlank()) {
                                                
                        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                queries,
                                new String [] {
                                        "Mã CT Phiếu Nhập", "Mã Phiếu Nhập", "Mã Mặt Hàng", "Số Lượng", "Đơn Giá Nhập", "Thành Tiền"
                                }));
                        return;
                    }
                    String query1 = "select * from chitietphieunhap where maphieunhap = \'" + mapn + "\'";

                    
                    System.out.println(query1);
                    rs = st.executeQuery(query1);
                    String[][] find_queries = new String[100][];
                    int i = 0;

                    while (rs.next()) {
                        String[] value = new String[100];
                        value[0] = rs.getString("MA_CTPN");
                        value[1] = rs.getString("MAPHIEUNHAP");
                        value[2] = rs.getString("MAMATHANG");
                        value[3] = rs.getString("SOLUONG");
                        value[4] = rs.getString("DONGIANHAP");
                        value[5] = rs.getString("THANHTIEN");             
                        find_queries[i] = value;
                        i+=1;
                    }
                    if (find_queries[0] == null) {
                    	JOptionPane.showMessageDialog(null,
                                "Không tìm thấy",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);

                    }
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    		find_queries,
                            new String [] {
                                    "Mã CT Phiếu Nhập", "Mã Phiếu Nhập", "Mã Mặt Hàng", "Số Lượng", "Đơn Giá Nhập", "Thành Tiền"
                            }));

                }
            }catch (SQLException ex) {
                Logger.getLogger(ctnh.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private String[][] removeElement(String[][] arr,int id) {
    	if (id < 0 || arr == null || id >= arr.length)
    		return arr;
    	
    	String[][] arr_temp = new String[arr.length-1][];
    	index -= 1;
    	
    	for (int i = 0,k=0;i<arr.length;i++) {
    		if (i == id) 
    			continue;
    		arr_temp[k++] = arr[i];
    	}
    	return arr_temp;
    }
    private void jButtoninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    	
    	if (evt.getSource() == jButtonin) {
            try (Connection conn = ConnectionUtils.getMyConnection()){
                if (conn != null) {
                    System.out.println("Connected to the database!");
                    Statement st =  conn.createStatement();
                    Statement st1 =  conn.createStatement();
                    String query = "insert into phieunhaphang values (\'" + truycap.maphieunhap +"\'"+ "," + "DATE " + "\'" + truycap.date + "\'"+ "," + tongtien + ","+ "\'" +truycap.cmnd+"\'" + ")";
                    st.executeQuery(query);
                    System.out.println(query);  
                    
                    JOptionPane.showMessageDialog(null,
                            "In thành công",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE); 
                    new QuanLyNhapHang().setVisible(true);
                    this.dispose();

                } else{
                    System.out.println("Failed to make connection!");
                }

            }catch (SQLException e) {

            } catch (ClassNotFoundException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
        }

    	}
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    	// xoa
        if (evt.getSource() == jButton5){
    		int row_select = jTable1.getSelectedRow();
    		if (row_select == -1) {
                JOptionPane.showMessageDialog(null,
                        "Vui lòng chọn chi tiết phiếu cần xóa",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                return;

    		}
    		if (row_select >=0 ) {
        		if (countNull(queries[row_select]) == 9) {
                    JOptionPane.showMessageDialog(null,
                            "Vui lòng chọn chi tiết phiếu tồn tại",
                            "ERROR",
                            JOptionPane.ERROR_MESSAGE);
                    return;
        		}
    		}

            try (Connection conn = ConnectionUtils.getMyConnection()){
                if (conn != null) {
                    System.out.println("Connected to the database!");
                    Statement st =  conn.createStatement();
                    Statement st1 =  conn.createStatement();

                    String ma_ctpn = String.valueOf(queries[row_select][0]);

                    String delete_query = "Delete from chitietphieunhap where ma_ctpn = " + "\'" + ma_ctpn + "\'";
                    System.out.println(delete_query);
                    st.executeUpdate(delete_query);

                    String sl = String.valueOf(queries[row_select][3]);
                    String mathang = String.valueOf(queries[row_select][2]);
                    String mapn = String.valueOf(queries[row_select][1]);
                    String thanhtien = String.valueOf(queries[row_select][5]);
                    String query2 = "update mathang set soluongton = soluongton - "  + sl + " where mamathang = " + "\'" + mathang +"\'";
                    st.executeUpdate(query2);
                    
                    
                    System.out.println(query2);
                    tongtien -= Integer.parseInt(thanhtien);
            		queries = removeElement(queries,row_select);

                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    		queries,
                            new String [] {
                                    "Mã CT Phiếu Nhập", "Mã Phiếu Nhập", "Mã Mặt Hàng", "Số Lượng", "Đơn Giá Nhập", "Thành Tiền"
                            }
                        ));

                } else{
                    System.out.println("Failed to make connection!");
                }

            }catch (SQLException e) {

            } catch (ClassNotFoundException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
        }
        JOptionPane.showMessageDialog(null,
                "Xóa thành công",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        return;

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    	// sua doi
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ctnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ctnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ctnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ctnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ctnh().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonin;

    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jLabeldongia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFielddongia;
    private int tongtien = 0;
    private javax.swing.JComboBox<String>jComboBox1;
    private int first_index = 0;

    String[][] queries = new String[1000][];
    int index = 0;
    // End of variables declaration//GEN-END:variables
}